-- 코드를 입력하세요
WITH RECURSIVE HOUR AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM HOUR
    WHERE NUM < 23
)

SELECT HOUR.NUM AS HOUR, COUNT(HOUR(ANIMAL_OUTS.DATETIME)) AS COUNT
FROM HOUR
LEFT JOIN ANIMAL_OUTS ON HOUR.NUM = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR.NUM
ORDER BY HOUR.NUM;